# Generated by Django 4.0.5 on 2022-06-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=22, verbose_name='Nombre')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=120, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('lanzamiento', models.IntegerField(verbose_name='Año de lazamiento')),
                ('tamanio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Duracion en minutos')),
                ('sinopsis', models.TextField(max_length=300, verbose_name='Sinopsis')),
                ('IDCompania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.compania')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=156, verbose_name='Apellidos')),
                ('usuario', models.CharField(max_length=200, unique=True, verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=15, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='PeliDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDdirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.director')),
                ('IDpelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDActor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
                ('IDpelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('Fantasía', 'Fantasía'), ('Acción', 'Acción'), ('Aventuras', 'Aventuras'), ('Suspenso', 'Suspenso'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Terror', 'Terror'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Comedia Dramatica', 'Comedia Dramatica'), ('Musical', 'Musical'), ('Comedia Romantica', 'Comedia Romantica')], max_length=20, verbose_name='Genero de la pelicula')),
                ('IDpeliculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=300, verbose_name='Frase')),
                ('IDactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
                ('IDpelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelicula')),
            ],
        ),
    ]
