# Generated by Django 4.0.5 on 2022-06-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(choices=[('Comedia Romantica', 'Comedia Romantica'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Comedia', 'Comedia'), ('Musical', 'Musical'), ('Aventuras', 'Aventuras'), ('Acción', 'Acción'), ('Drama', 'Drama'), ('Comedia Dramatica', 'Comedia Dramatica'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Fantasía', 'Fantasía')], max_length=20, verbose_name='Genero de la pelicula'),
        ),
    ]
